import './globals.css'
import { Quicksand } from 'next/font/google'


import Navbar03 from './components/Navbars/Navbar03'

export const dynamic = 'force-dynamic'

const inter = Quicksand({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar03 />
        {children}
      </body>
    </html>
  )
}
